Tue 21: Added urxvt and dunst

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -3,30 +3,37 @@
 # Update - Updates repo to local setup
 
 # Functions
-successfulCommand () {
-    if [ $? -eq 0 ]; then
-        true
-    else
-        false
+PASS() {
+    echo -e '\e[32m[✓]'"$@"'\e[0m'
+}
+
+FAIL() {
+    echo -e '\e[31m[X]'"$@"'\e[0m'
+}
+
+clone () {
+    if [ $1 = "Wallpapers" ]; then
+        cp ~/Wallpapers/* ~/.dotfiles/wallpaper/ &> /dev/null
+        case $? in
+            0)  PASS "Wallpapers Updated"
+                ;;
+            *)  FAIL "Wallpapers Failed"
+                ;;
+        esac
+    elif [ $1 = "Scripts" ]; then
+        cp ~/.scripts/* ~/.dotfiles/bin &> /dev/null
+        case $? in 
+            0)  PASS "Bin Updated"
+                ;;
+            *)  FAIL "Bin Failed"
+                ;;
+        esac
     fi
 }
 
 # Header
 echo -e '\e[34mUpdating Dotfiles:\e[0m'
 
-# Wallpapers
-cp ~/Wallpapers/* ~/.dotfiles/wallpaper/
-if [ successfulCommand ]; then
-    echo -e '\e[32m[✓] Wallpapers Updated\e[0m'
-else 
-    echo -e '\e[31m[X] Wallpapers Failed$\e[0m'
-fi
-
-# Scripts
-cp ~/.scripts/* ~/.dotfiles/bin/
-if [ successfulCommand ]; then
-    echo -e '\e[32m[✓] Bin Updated\e[0m'
-else
-    echo -e '\e[31m[X] Bin Failed$\e[0m'
-fi
-
+# Checks
+clone "Wallpapers"
+clone "Scripts"
